{application,neuron,
             [{modules,['Elixir.Neuron','Elixir.Neuron.Config',
                        'Elixir.Neuron.ConfigUtils',
                        'Elixir.Neuron.Connection',
                        'Elixir.Neuron.Connection.Http',
                        'Elixir.Neuron.Fragment',
                        'Elixir.Neuron.JSONParseError',
                        'Elixir.Neuron.MissingFragmentsError',
                        'Elixir.Neuron.Response','Elixir.Neuron.Store']},
              {optional_applications,[jason]},
              {applications,[kernel,stdlib,elixir,logger,httpoison,jason]},
              {description,"A GraphQL client for elixir."},
              {registered,[]},
              {vsn,"5.1.0"}]}.
