import fs from 'fs/promises';
import path from 'path';
import {
  getAllMarkdownFiles,
  getJSONFileContent,
  getNginxRedirects,
  getReversedAliasPaths,
  normalizePathWithSlash,
} from './common.js';

// Cloudflare Pages CF-N.1: generates the redirect config for Pages from the
// SAME source data (public/content/{redirects,aliases,shorten-redirects}.json)
// that scripts/generate-nginx-redirect-map.ts turns into the Railway/nginx map,
// so the two deploy targets serve the same redirects.
//
// Cloudflare Pages' `_redirects` file caps out at 2,000 static rules + 100
// dynamic (splat/placeholder) rules, 2,100 total:
// https://developers.cloudflare.com/pages/configuration/redirects/
// The site's full redirect map already exceeds 2,000 entries (see
// docs/cf-migration/pages-deploy.md), so `_redirects` alone cannot carry every
// rule. Design: `_redirects` ships the first 2,000 rules as a fast edge-level
// path (no Function invocation); the FULL map ships as
// functions/_generated-redirect-map.ts and is enforced with zero drops by
// functions/_middleware.ts, which has no rule-count limit. Run
// scripts/verify-cf-redirects.ts to prove the full map has no gaps vs the
// nginx map.
const REDIRECTS_STATIC_CAP = 2000;

const CONTENT_DIR = path.join(process.cwd(), 'public/content');
const SHORTEN_REDIRECTS_JSON_PATH = path.join(
  CONTENT_DIR,
  'shorten-redirects.json',
);

// `_redirects` must live at the root of the Pages build output (Next copies
// `public/*` to the root of `out/`, so `public/content/_redirects` would land
// at `out/content/_redirects`, the wrong place). Write it straight into `out/`
// instead, same convention scripts/generate-rss.ts already uses for its feed
// files. Override via CF_REDIRECTS_OUT_DIR for testing against a different
// output tree.
const OUT_DIR = process.env.CF_REDIRECTS_OUT_DIR
  ? path.resolve(process.env.CF_REDIRECTS_OUT_DIR)
  : path.join(process.cwd(), 'out');
const REDIRECTS_FILE_OUTPUT_PATH = path.join(OUT_DIR, '_redirects');

// functions/ lives at the repo root (sibling to `out/`), Cloudflare Pages'
// convention for Pages Functions. Override via CF_REDIRECTS_FUNCTIONS_DIR for
// testing without touching the real functions/ directory.
const FUNCTIONS_DIR = process.env.CF_REDIRECTS_FUNCTIONS_DIR
  ? path.resolve(process.env.CF_REDIRECTS_FUNCTIONS_DIR)
  : path.join(process.cwd(), 'functions');
const GENERATED_MAP_OUTPUT_PATH = path.join(
  FUNCTIONS_DIR,
  '_generated-redirect-map.ts',
);

/**
 * Mirrors scripts/generate-nginx-redirect-map.ts's getValidShortenPaths
 * exactly (same three validity checks: alias match, redirect match, existing
 * markdown file). Duplicated rather than imported so this script stays
 * independently reviewable; keep in sync if the nginx generator's filter
 * changes.
 */
async function getValidShortenPaths(
  alias: Record<string, string> = {},
): Promise<Record<string, string>> {
  const shortenRedirects = await getJSONFileContent(
    SHORTEN_REDIRECTS_JSON_PATH,
  );
  const markdownFiles = (await getAllMarkdownFiles(CONTENT_DIR)).map(
    slugs => `/${slugs.join('/')}`,
  );

  const aliasEntries = Object.entries(alias).map(([key, value]) => [
    normalizePathWithSlash(key),
    normalizePathWithSlash(value),
  ]);

  return Object.fromEntries(
    Object.entries(shortenRedirects).filter(([, targetUrl]) => {
      if (
        aliasEntries.some(
          ([aliasURL, aliasTarget]) =>
            aliasTarget === targetUrl || aliasURL === targetUrl,
        )
      ) {
        return true;
      }
      return markdownFiles.includes(targetUrl as string);
    }),
  );
}

function flattenRules(
  alias: Record<string, string>,
  redirects: Record<string, string>,
  shortenRedirects: Record<string, string>,
): [string, string][] {
  // Same precedence as generate-nginx-redirect-map.ts: alias, then redirects,
  // then shortenRedirects, each later map overriding the earlier on conflict.
  const merged: Record<string, string> = {};
  for (const obj of [alias, redirects, shortenRedirects]) {
    for (const [key, value] of Object.entries(obj)) {
      merged[normalizePathWithSlash(key)] = normalizePathWithSlash(value);
    }
  }
  return Object.entries(merged)
    .filter(([source, target]) => target && source !== target)
    .sort(([a], [b]) => a.localeCompare(b));
}

async function generateCfRedirects() {
  const alias = await getReversedAliasPaths();
  const redirects = await getNginxRedirects();
  const shortenRedirects = await getValidShortenPaths(alias);

  const rules = flattenRules(alias, redirects, shortenRedirects);
  console.log(
    `Generated ${rules.length} redirect rules (alias + redirects + shorten).`,
  );

  await fs.mkdir(FUNCTIONS_DIR, { recursive: true });
  const generatedTs =
    '// AUTO-GENERATED by scripts/generate-cf-redirects.ts. Do not hand-edit.\n' +
    '// Full redirect map (alias + nginx-map redirects + validated shorten\n' +
    '// links), consumed by functions/_middleware.ts. Every rule is present\n' +
    '// here (unlike out/_redirects, which Cloudflare Pages caps at 2,000\n' +
    '// static rules).\n' +
    `export const REDIRECT_MAP: Record<string, string> = ${JSON.stringify(
      Object.fromEntries(rules),
      null,
      2,
    )};\n`;
  await fs.writeFile(GENERATED_MAP_OUTPUT_PATH, generatedTs);
  console.log(
    `Full redirect map written to ${GENERATED_MAP_OUTPUT_PATH} (${rules.length} rules).`,
  );

  const capped = rules.slice(0, REDIRECTS_STATIC_CAP);
  if (rules.length > REDIRECTS_STATIC_CAP) {
    console.warn(
      `${rules.length} redirect rules exceed Cloudflare Pages' 2,000 static-rule ` +
        `cap; out/_redirects carries the first ${REDIRECTS_STATIC_CAP} (sorted, ` +
        'deterministic), functions/_middleware.ts enforces the remaining rules ' +
        'with no drop.',
    );
  }
  const header =
    '# AUTO-GENERATED by scripts/generate-cf-redirects.ts. Do not hand-edit.\n' +
    `# ${rules.length} total redirect rules; Cloudflare Pages caps _redirects at\n` +
    '# 2,000 static rules, so this file carries the first 2,000 as a fast edge\n' +
    '# path. The full set is enforced with no drops by functions/_middleware.ts.\n';
  const body = capped
    .map(([source, target]) => `${source} ${target} 301`)
    .join('\n');
  await fs.mkdir(OUT_DIR, { recursive: true });
  await fs.writeFile(REDIRECTS_FILE_OUTPUT_PATH, `${header}${body}\n`);
  console.log(
    `_redirects written to ${REDIRECTS_FILE_OUTPUT_PATH} (${capped.length} rules).`,
  );
}

generateCfRedirects().catch(error => {
  console.error('Error generating CF Pages redirects:', error);
  process.exit(1);
});
