import fs from 'fs/promises';
import path from 'path';

// Excludes two file classes from the Cloudflare Pages UPLOAD, not from the
// build. `.assetsignore` uses gitignore syntax and must live at the root of
// the deployed directory (Cloudflare docs; confirmed against wrangler's own
// bundled matcher, which resolves it as `path.resolve(dir, '.assetsignore')`
// on the `out` directory passed to `wrangler pages deploy`).
//
// 1. `/content/**/*.md`: raw markdown copies of every note, written by
//    scripts/export-markdown.ts into public/content/ (~2,025 files). No
//    in-repo route reads them back from their live URL; [...slug].tsx renders
//    notes from the same files at BUILD time, not at request time. Excluding
//    them is reversible: delete this line to re-include them. Non-markdown
//    assets under content/** (images, PDFs) stay uploaded; pages embed them
//    by live URL (see functions/lib/oversize-assets.ts).
// 2. `/content/db/vault.parquet`: a duplicate of db/vault.parquet (~22 MB),
//    also written by export-markdown.ts. Every in-repo consumer
//    (scripts/memo-nft-report.ts, src/lib/db/utils.ts) reads db/vault.parquet;
//    grepping the repo for "content/db" turns up zero references. Only this
//    one file is excluded, not the rest of the duplicated content/db/
//    directory (schema.sql, load.sql, processing_metadata*.parquet).
const OUT_DIR = process.env.CF_ASSETSIGNORE_OUT_DIR ?? path.join(process.cwd(), 'out');
const ASSETSIGNORE_OUTPUT_PATH = path.join(OUT_DIR, '.assetsignore');

const PATTERNS = ['/content/**/*.md', '/content/db/vault.parquet'];

async function generateAssetsIgnore() {
  const header =
    '# AUTO-GENERATED by scripts/generate-assetsignore.ts. Do not hand-edit.\n' +
    '# Excludes files from the Cloudflare Pages upload only; they still exist\n' +
    '# in the build output. Reversible: remove a line to re-include that file.\n';
  await fs.mkdir(OUT_DIR, { recursive: true });
  await fs.writeFile(ASSETSIGNORE_OUTPUT_PATH, `${header}${PATTERNS.join('\n')}\n`);
  console.log(`.assetsignore written to ${ASSETSIGNORE_OUTPUT_PATH} (${PATTERNS.length} patterns).`);
}

generateAssetsIgnore().catch(error => {
  console.error('Error generating .assetsignore:', error);
  process.exit(1);
});
