name: Generate Redirects

on:
  workflow_dispatch: # Keep manual trigger
  push:
    branches:
      - main
    paths:
      - 'db/vault.parquet'

concurrency:
  group: ${{ github.repository }}-gen-redirect-workflow
  cancel-in-progress: false

env:
  VAULT_ADDR: ${{ secrets.VAULT_ADDR }}

jobs:
  generate-redirects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout contents repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DWARVES_PAT }}
          submodules: recursive
          fetch-depth: 1

      - name: Get changed files from Memo
        id: changed-files
        uses: tj-actions/changed-files@v46.0.5
        with:
          separator: ','

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - uses: actions/github-script@v7
        if: steps.changed-files.outputs.all_changed_files != ''
        id: normalize-paths
        with:
          script: |
            const files = '${{ steps.changed-files.outputs.all_changed_files }}'.split(',').filter((f) => {
              if (!f) {
                return false;
              }
              // Filter out files that are not markdown files or do not start with 'vault/'
              return (f.endsWith('.md') || f.endsWith('.mdx')) && f.startsWith('vault/');
            });
            return files;
          result-encoding: string

      - name: Run script with files
        if: steps.normalize-paths.outputs.result != ''
        run: |
          npx tsx scripts/generate-redirects.ts --files='${{ steps.normalize-paths.outputs.result }}'

      - name: Commit and push changes
        uses: ./.github/actions/git-commit-push
        with:
          commit-message: 'chore(ci): redirects'

      - name: Notify Discord on Success
        if: success() && steps.normalize-paths.outputs.result != ''
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: '✅ Redirects Generated Successfully'
          description: 'Redirect mappings have been generated and committed for changed markdown files'
          color: 0x00ff00

      - name: Notify Discord on Failure
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: '❌ Redirect Generation Failed'
          description: 'Failed to generate redirect mappings. Please check the workflow logs.'
          color: 0xff0000
